# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Monitor Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "AdamWHY2K"
    assignees:
      - "AdamWHY2K"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(dev-deps)"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
